version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

