version: '3.8'

services:
  db:
    image: postgres:14
    container_name: erp-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-erpuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-erppassword}
      POSTGRES_DB: ${POSTGRES_DB:-erpdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
