# 개발 환경 설정 - 공통 설정 상속 후 개발 전용 설정만 오버라이드

# Swagger API 문서 서버 URL (개발)
swagger:
  server-url: https://dev-erp-api.dooson.it

# CORS 설정 (개발 환경용)
cors:
  allowed-origins: https://dev-erp.dooson.it,https://dev-erp-api.dooson.it,http://localhost:3000