spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  data:
    web:
      pageable:
        max-page-size: 200

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
        default_batch_fetch_size: 200
    open-in-view: false

user:
  default-password: ${USER_DEFAULT_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

swagger:
  server-url: https://dev-erp-api.dooson.it

cors:
  allowed-origins: https://dev-erp.dooson.it,https://dev-erp-api.dooson.it