spring:
  data:
    web:
      pageable:
        max-page-size: 200

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
        default_batch_fetch_size: 200
    open-in-view: false

user:
  default-password: ${USER_DEFAULT_PASSWORD}

session:
  timeout:
    default-seconds: ${SESSION_TIMEOUT_DEFAULT_SECONDS}
    auto-login-seconds: ${SESSION_TIMEOUT_AUTO_LOGIN_SECONDS}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always
