spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none       # 운영환경: DDL 자동 생성/수정/검증 전부 금지
    show-sql: false        # 운영환경에서는 SQL 출력 비활성화 (보안 및 성능 이슈 방지)

  flyway:
    enabled: true
    locations: classpath:db/migration/prod  # 운영용 마이그레이션 스크립트 경로

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN                                # Hibernate SQL 로그는 경고 이상만 출력
    org.hibernate.type.descriptor.sql.BasicBinder: WARN    # 바인딩 값 출력도 경고 수준 제한