spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none  # Hibernate가 테이블을 자동으로 생성/수정하지 않음 (Flyway가 스키마 관리함)
    show-sql: true    # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true  # SQL 출력 포맷팅

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/seed

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

user:
  default-password: ${USER_DEFAULT_PASSWORD}

session:
  timeout:
    default-seconds: 3600      # 일반 로그인 (1시간)
    auto-login-seconds: 604800 # 자동 로그인 (7일)

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always