# 로컬 환경 설정 - 공통 설정 상속 후 로컬 전용 설정만 오버라이드

# Swagger API 문서 서버 URL (로컬)
swagger:
  server-url: http://localhost:8080

# CORS 설정 (로컬 개발용)
cors:
  allowed-origins: http://localhost:8080,http://localhost:3000

