spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none  # Hibernate가 테이블을 자동으로 생성/수정하지 않음 (Flyway가 스키마 관리함)
    show-sql: true    # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true  # SQL 출력 포맷팅
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/seed

logging:
  level:
    org.flywaydb.core: INFO
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: DEBUG  # 실행 SQL만 출력
    org.flywaydb.core.internal.parser.Parser: INFO  # 파싱 로그는 생략
    org.hibernate.SQL: DEBUG  # SQL 출력
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG  # 바인딩 파라미터

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 15m
  refresh-token-validity: 7d