# 로컬 환경 설정
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

  data:
    web:
      pageable:
        max-page-size: 200

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/erpdb
    username: erpuser
    password: erppassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time-zone: UTC
          batch-size: 50
          order-inserts: true
          order-updates: true
        default-batch-fetch-size: 200
        format-sql: true
        highlight-sql: true
    open-in-view: false

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    shutdown:
      access: unrestricted
