spring:
  data:
    web:
      pageable:
        max-page-size: 200  # 최대 페이지 크기 제한

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none  # Hibernate가 테이블을 자동으로 생성/수정하지 않음 (Flyway가 스키마 관리함)
    show-sql: true    # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true  # SQL 출력 포맷팅

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/seed

user:
  default-password: ${USER_DEFAULT_PASSWORD}

session:
  timeout:
    default-seconds: ${SESSION_TIMEOUT_DEFAULT_SECONDS}
    auto-login-seconds: ${SESSION_TIMEOUT_AUTO_LOGIN_SECONDS}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always
