INSERT INTO users (id,
                   company_id,
                   login_id,
                   username,
                   password_hash,
                   phone_number,
                   password_reset_at,
                   last_login_at,
                   created_at,
                   updated_at,
                   created_by,
                   updated_by,
                   deleted)
VALUES (nextval('users_seq'),
        1,
        'admin',
        '관리자',
        '$2a$10$HXd48McVwdCkeV9XobmxResJ72XpTMpyvZPC9FUJB2edwstaMknma',
        '010-1234-5678',
        NULL,
        NULL,
        NOW(),
        NOW(),
        'system',
        'system',
        false);