package com.lineinc.erp.api.server.domain.labor.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum LaborWorkType {
    ETC("기타", 0),
    OUTSOURCING("용역", 1),
    GAS_WELDER("가스용접공", 2),
    SCAFFOLDING("가시설공", 3),
    CONSTRUCTION_MACHINE_OPERATOR("건설기계운전원", 4),
    CONSTRUCTION_SAFETY("건설안전공", 5),
    HOISTING("견출공", 6),
    MEASUREMENT("계측공", 7),
    STRUCTURE("구조물공", 8),
    EXCAVATOR_OPERATOR("굴삭기(운전원)", 9),
    EXCAVATOR_DRIVER("굴착기(운전원)", 10),
    GROUTING("그라우팅공", 11),
    GRADER_OPERATOR("그레이더(운전원)", 12),
    DUMP_TRUCK_OPERATOR("덤프트럭(운전원)", 13),
    PAINTER("도색공", 14),
    LOADER_OPERATOR("로우더(운전원)", 15),
    ROLLER_OPERATOR("롤러(운전원)", 16),
    CARPENTER("목공", 17),
    BLASTING("발파공", 18),
    WATERPROOFING("방수공", 19),
    LOGGING("벌목공", 20),
    BORING("보링공", 21),
    GENERAL_LABORER("보통인부", 22),
    SUPPORT_WORKER("부대공", 23),
    SCAFFOLD_WORKER("비계공", 24),
    NDT_TESTER("비파괴시험공", 25),
    OFFICE_ASSISTANT("사무보조", 26),
    STONE_WORKER("석공", 27),
    SITE_MANAGER("현장소장", 28),
    SHOT_BLASTER("쇼트공", 29),
    SIGNAL_MAN("신호수", 30),
    ASPHALT_PLANT_OPERATOR("아스팔트플랜트(운전원)", 31),
    ASPHALT_FINISHER_OPERATOR("아스팔트피니셔(운전원)", 32),
    SAFETY_FACILITY("안전시설공", 33),
    LIQUID_WATERPROOFING("액체방수공", 34),
    PUMP_OPERATOR("양수공", 35),
    GRINDER("연마공", 36),
    WELDER("용접공", 37),
    WOO_OSU("우오수공", 38),
    GENERAL_MACHINE_OPERATOR("일반기계운전원", 39),
    WORK_LEADER("작업반장", 40),
    FORKLIFT_OPERATOR("지게차(운전원)", 41),
    LANE_PAINTER("차선도색공", 42),
    ROCK_DRILLER("착암공", 43),
    DEMOLITION("철거공", 44),
    STEEL_FRAME("철골공", 45),
    REBAR("철근공", 46),
    CLEANER("청소원", 47),
    SURVEYOR("측량공", 48),
    COMPRESSOR_OPERATOR("콤퓨레샤(운전원)", 49),
    CRANE_OPERATOR("크레인(운전원)", 50),
    TOWER_CRANE_OPERATOR("타워크레인(운전원)", 51),
    EARTHWORK("토공", 52),
    SHEET_PILE("토류판공", 53),
    SPECIAL_LABORER("특별인부", 54),
    PANEL_ASSEMBLER("판넬조립공", 55),
    PAVING("포설공", 56),
    PAVING_WORKER("포장공", 57),
    ROCK_BREAKING("할석공", 58),
    CORRUGATED_SHEET("함석공", 59),
    FORMWORK_CARPENTER("형틀목공", 60),
    HOIST_OPERATOR("호이스트운전원", 61),
    TRUCK_DRIVER("화물차(운전원)", 62),
    EXPLOSIVE_HANDLER("화약취급공", 63),
    PIPE_WORKER("흄관공", 64),
    EARTH_RETAINING("흙막이공", 65);

    private final String label;
    private final int order;
}
