ALTER TABLE company
    ADD deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE role
    ADD deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE users
    ADD deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE users
    DROP COLUMN locked_at;